USE music4u;

SELECT * FROM forma_pagamento;
SELECT * FROM plano;
SELECT * FROM usuario;
SELECT * FROM comprar_plano;
SELECT * FROM artista;
SELECT * FROM musica;
SELECT * FROM play;

-- Resposta da primeira pergunta
SELECT COUNT(*) AS USUARIOS_FREE FROM usuario
WHERE ID_PLANO = 1;

-- Resposta da segunda pergunta
SELECT COUNT(*) AS TIMES_PLAYED FROM play
WHERE ID_ARTISTA = 1;

-- Resposta da terceira pergunta
SELECT DISTINCT A.ID, A.NOME AS ARTISTA FROM PLAY P
JOIN ARTISTA A on P.ID_ARTISTA = A.ID;

-- Resposta da quarta pergunta
SELECT A.NOME AS ARTISTA, M.NOME AS MUSICA, M.DATA_PUBLICACAO FROM MUSICA M
JOIN ARTISTA A ON M.ID_ARTISTA = A.ID
WHERE DATA_PUBLICACAO 
BETWEEN '2021-01-01' AND '2021-12-31' 
ORDER BY DATA_PUBLICACAO;

-- Resposta da quinta pergunta
SELECT A.NOME AS ARTISTA, M.NOME AS MUSICA, M.DATA_PUBLICACAO FROM ARTISTA A
JOIN MUSICA M ON A.ID = M.ID_ARTISTA
ORDER BY DATA_PUBLICACAO;

-- Resposta da sexta pergunta
SELECT U.NOME, P.NIVEL AS PLANO FROM USUARIO U
JOIN PLANO P ON U.ID_PLANO = P.ID
WHERE P.ID > 1;

-- Resposta da setima pergunta
SELECT NOME AS ARTISTA_POP FROM ARTISTA
WHERE DESCRICAO = "POP MUSIC";

-- Resposta da oitava pergunta
SELECT DISTINCT F.DESCRICAO AS FORMA_PAGAMENTO FROM FORMA_PAGAMENTO F
JOIN USUARIO U ON F.ID = U.ID_FORMA_PAGAMENTO;

-- Resposta da nona pergunta
SELECT * FROM COMPRAR_PLANO
WHERE DATA_COMPRA = '2022-11-01';

-- Resposta da decima pergunta 
Select A.NOME AS ARTISTA, A.DESCRICAO AS ESTILO_MUSICA, F.DESCRICAO AS FORMA_PAGAMENTO FROM ARTISTA A
JOIN FORMA_PAGAMENTO F ON A.ID_FORMA_PAGAMENTO = F.ID
WHERE A.ID = 10